# Generated by Django 5.1.1 on 2024-10-23 23:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_usuario')
    ]

    operations = [
        migrations.CreateModel(
            name='Punto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('orden', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PuntoInteres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
                ('punto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interes', to='ruta.punto')),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('dificultad', models.CharField(choices=[('facil', 'Fácil'), ('moderada', 'Moderada'), ('dificil', 'Difícil')], default='moderada', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('distancia_km', models.FloatField()),
                ('tiempo_estimado_minutos', models.IntegerField()),
                ('publica', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rutas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='punto',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos', to='ruta.ruta'),
        ),
        migrations.CreateModel(
            name='RutaCompartida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ruta.ruta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('ruta', 'usuario')},
            },
        ),
        migrations.AddField(
            model_name='ruta',
            name='compartida_con',
            field=models.ManyToManyField(blank=True, related_name='rutas_compartidas_conmigo', through='ruta.RutaCompartida', to=settings.AUTH_USER_MODEL),
        ),
    ]
