# Generated by Django 5.1.2 on 2024-12-04 15:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruta', '0003_ruta_puntaje_comentario_puntaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['-created_at']},
        ),
    ]
