# Generated by Django 5.1.1 on 2024-10-16 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0003_demo_ruta'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuntoInteres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
                ('punto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interes', to='trek.punto')),
            ],
        ),
    ]
