# Generated by Django 5.1.1 on 2024-10-19 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trek', '0004_puntointeres'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='ruta',
            name='publica',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='RutaCompartida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trek.ruta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('ruta', 'usuario')},
            },
        ),
        migrations.AddField(
            model_name='ruta',
            name='compartida_con',
            field=models.ManyToManyField(blank=True, related_name='rutas_compartidas_conmigo', through='trek.RutaCompartida', to=settings.AUTH_USER_MODEL),
        ),
    ]
