# Generated by Django 5.1.1 on 2024-10-02 17:02

from django.contrib.auth.hashers import make_password
from django.db import migrations
from django.db import models


def create_base_users(apps, schema):
    Usuario = apps.get_model('user.Usuario')

    Usuario.objects.create(
        username='default',
        email='default@itrek.com',
    )

    Usuario.objects.create(
        username='admin',
        email='admin@itrek.com',
        password=make_password('1234'),
        is_staff=True,
        is_superuser=True
    )


def delete_base_users(apps, schema):
    Usuario = apps.get_model('user.Usuario')

    Usuario.objects.filter(username__in=['default', 'admin']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            create_base_users,
            delete_base_users,
        ),
    ]
